.TH "APDUResponse.cpp" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APDUResponse.cpp \- Implements the class APDUResponse represents the APDU response sent by the card\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <winscard\&.h>\fP
.br
\fC#include <QtCore/QByteArray>\fP
.br
\fC#include <QtCore/QTextStream>\fP
.br
\fC#include 'APDUResponse\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implements the class APDUResponse represents the APDU response sent by the card\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
