.TH "APDUCommand.cpp" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APDUCommand.cpp \- Implements the class APDUCommand represents the APDU command\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QTextStream>\fP
.br
\fC#include <qalgorithms\&.h>\fP
.br
\fC#include 'APDUCommand\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implements the class APDUCommand represents the APDU command\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
