.TH "APDUResponse.h" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APDUResponse.h \- Header file for APDUResponse class File is contains class APDUResponse represents the APDU response sent by the card\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <winscard\&.h>\fP
.br
\fC#include <QByteArray>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSmartcards::APDUResponse\fP"
.br
.RI "This class represents the APDU response sent by the card\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSmartcards\fP"
.br
.RI "Namespace of smartcard classes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for APDUResponse class File is contains class APDUResponse represents the APDU response sent by the card\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
