.TH "baseexceptions.h" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baseexceptions.h \- Header file for \fBBaseExceptions\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdexcpt\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseExceptions\fP"
.br
.RI "This class must implement a std::exception in Qt-style class\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for \fBBaseExceptions\fP class\&. 

File is contains class \fBBaseExceptions\fP must implement a std::exception in Qt-style class 
.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
