.TH "baseexceptions.cpp" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baseexceptions.cpp \- Implements the baseexceptions class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include 'baseexceptions\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implements the baseexceptions class\&. 

File is contains implements the class \fBBaseExceptions\fP, must implement a std::exception in Qt-style class 
.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
