.TH "cardevent.cpp" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cardevent.cpp \- Implements the CardEvent class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QThread>\fP
.br
\fC#include <QtCore/QMutex>\fP
.br
\fC#include <QtCore/QHash>\fP
.br
\fC#include <winscard\&.h>\fP
.br
\fC#include 'cardevent\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implements the CardEvent class\&. 

File is contains source of class CardEvent must implement a card detection mechanism\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
