.TH "NativeSCard.h" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NativeSCard.h \- Header file for WinSCard class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'APDUResponse\&.h'\fP
.br
\fC#include 'APDUCommand\&.h'\fP
.br
\fC#include 'WinSCardErr\&.h'\fP
.br
\fC#include <QtCore/qmap\&.h>\fP
.br
\fC#include <QtCore/quuid\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSmartcards::SCARD_ATTR_VALUE\fP"
.br
.RI "Values for AttrId of SCardGetAttrib\&. "
.ti -1c
.RI "class \fBSmartcards::ReadersStates\fP"
.br
.RI "Interface class for Smart Card Tracking Functions\&. Contains readers states\&. "
.ti -1c
.RI "class \fBSmartcards::WinSCard\fP"
.br
.RI "This class must implement a winscard api\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSmartcards\fP"
.br
.RI "Namespace of smartcard classes\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSmartcards::SCOPE\fP : DWORD { \fBSmartcards::User\fP, \fBSmartcards::Terminal\fP, \fBSmartcards::System\fP }
.RI "SCOPE context\&. ""
.br
.ti -1c
.RI "enum \fBSmartcards::SHARE\fP : DWORD { \fBSmartcards::Exclusive\fP = 1, \fBSmartcards::Shared\fP, \fBSmartcards::Direct\fP }
.RI "SHARE mode enumeration\&. ""
.br
.ti -1c
.RI "enum \fBSmartcards::PROTOCOL\fP : DWORD { \fBSmartcards::Undefined\fP = 0x00000000, \fBSmartcards::T0\fP = 0x00000001, \fBSmartcards::T1\fP = 0x00000002, \fBSmartcards::T0orT1\fP = T0 | T1 }
.RI "PROTOCOL enumeration\&. ""
.br
.ti -1c
.RI "enum \fBSmartcards::DISCONNECT\fP : DWORD { \fBSmartcards::Leave\fP, \fBSmartcards::Reset\fP, \fBSmartcards::Unpower\fP, \fBSmartcards::Eject\fP }
.RI "DISCONNECT action enumeration\&. ""
.br
.ti -1c
.RI "enum \fBSmartcards::CARD_STATUS_STATE\fP : DWORD { \fBSmartcards::Unaware\fP = 0x00000000, \fBSmartcards::Ignore\fP = 0x00000001, \fBSmartcards::Changed\fP = 0x00000002, \fBSmartcards::Unknown\fP = 0x00000004, \fBSmartcards::Unvailable\fP = 0x00000008, \fBSmartcards::Empty\fP = 0x00000010, \fBSmartcards::Present\fP = 0x00000020, \fBSmartcards::ATRMatch\fP = 0x00000040, \fBSmartcards::ExclusiveStatus\fP = 0x00000080, \fBSmartcards::InUse\fP = 0x00000100, \fBSmartcards::Mute\fP = 0x00000200, \fBSmartcards::Unpowered\fP = 0x00000400 }
.RI "Card status enumeration, used by the class ReaderStates\&. ""
.br
.ti -1c
.RI "enum \fBSmartcards::CARD_STATE\fP : DWORD { \fBSmartcards::Absent\fP = SCARD_ABSENT, \fBSmartcards::PresentState\fP = SCARD_PRESENT, \fBSmartcards::Swallowed\fP = SCARD_SWALLOWED, \fBSmartcards::Powered\fP = SCARD_POWERED, \fBSmartcards::Negotable\fP = SCARD_NEGOTIABLE, \fBSmartcards::Specific\fP = SCARD_SPECIFIC }
.RI "Card state enumeration, used by the GetCardStatus function\&. ""
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for WinSCard class\&. 

Header file for WinSCard class and auxiliary classes\&.
.PP
File is contains source of class WinSCard must implement a winscard api\&.
.PP
File is contains class WinSCard must implement a winscard api\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
