.TH "NativeSCard.cpp" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NativeSCard.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVector>\fP
.br
\fC#include <winscard\&.h>\fP
.br
\fC#include 'NativeSCard\&.h'\fP
.br
\fC#include 'scardexception\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
