.TH "scardexception.cpp" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scardexception.cpp \- Implements the \fBSCardException\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qmap\&.h>\fP
.br
\fC#include <QtCore/QObject>\fP
.br
\fC#include 'scardexception\&.h'\fP
.br
\fC#include 'winscarderr\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implements the \fBSCardException\fP class\&. 

File is contains source of class \fBSCardException\fP must implement a card exception based on WinSCard errors 
.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
