.TH "scardexception.h" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scardexception.h \- Header file for \fBSCardException\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baseexceptions\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSCardException\fP"
.br
.RI "This class must implement a card exception based on WinSCard errors\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for \fBSCardException\fP class\&. 

File is contains class \fBSCardException\fP must implement a card exception based on WinSCard errors 
.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
