.TH "SCardException" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCardException \- This class must implement a card exception based on WinSCard errors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scardexception\&.h>\fP
.PP
Inherits \fBBaseExceptions\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSCardException\fP (long code) noexcept"
.br
.RI "error code constructor\&. "
.ti -1c
.RI "virtual \fB~SCardException\fP () noexcept"
.br
.RI "Destructor\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBgetMessage\fP (long code)"
.br
.RI "static function returns Qt-String message from winscard long error code "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class must implement a card exception based on WinSCard errors\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SCardException::SCardException (long code)\fC [explicit]\fP, \fC [noexcept]\fP"

.PP
error code constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcode\fP long error code 
.RE
.PP

.SS "SCardException::~SCardException ()\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "QString SCardException::getMessage (long code)\fC [static]\fP"

.PP
static function returns Qt-String message from winscard long error code 
.PP
\fBParameters:\fP
.RS 4
\fIcode\fP long error code 
.RE
.PP
\fBReturns:\fP
.RS 4
Qt-string error message from errorMessages map or message from winAPI FormatMessage function 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
