.TH "scdbmng_funcs" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scdbmng_funcs \- Smart Card Database Management Functions
.SS "Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::AddReaderToGroup\fP (const QString &ReaderName, const QString &GroupName)"
.br
.RI "Adds a reader to group to 'GroupName'\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::ForgetCardType\fP (const QString &cardName)"
.br
.RI "Removes an introduced smart card from the smart card subsystem\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::ForgetReader\fP (const QString &ReaderName)"
.br
.RI "removes a previously introduced reader from control by the smart card subsystem\&. It is removed from the smart card database, including from any reader group that it may have been added to\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::ForgetReaderGroup\fP (const QString &GroupName)"
.br
.RI "Removes a previously introduced smart card reader group from the smart card subsystem\&. Although this function automatically clears all readers from the group, it does not affect the existence of the individual readers in the database\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::IntroduceReader\fP (const QString &ReaderName, const QString &DeviceName)"
.br
.RI "Introduces a new name for an existing smart card reader\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::IntroduceReaderGroup\fP (const QString &GroupName)"
.br
.RI "Introduces a reader group to the smart card subsystem\&. However, the reader group is not created until the group is specified when adding a reader to the smart card database\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::RemoveReaderFromGroup\fP (const QString &ReaderName, const QString &GroupName)"
.br
.RI "Removes a reader from an existing reader group\&. This function has no effect on the reader\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::IntroduceCardType\fP (const QString &cardName, const QVector< QUuid > &guidInterfaces, const QByteArray &cardAtr, const QByteArray &cardAtrMask, QUuid *pguidPrimaryProvider=nullptr)"
.br
.RI "Introduces a smart card to the smart card subsystem (for the active user) by adding it to the smart card database\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::IntroduceCardType\fP (const QString &cardName, const QVector< QUuid > &guidInterfaces, const QByteArray &cardAtr, QUuid *pguidPrimaryProvider=nullptr)"
.br
.RI "Introduces a smart card to the smart card subsystem (for the active user) by adding it to the smart card database\&. Match by ATR and interfaces specified\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::IntroduceCardType\fP (const QString &cardName, const QByteArray &cardAtr, const QByteArray &cardAtrMask, QUuid *pguidPrimaryProvider=nullptr)"
.br
.RI "Introduces a smart card to the smart card subsystem (for the active user) by adding it to the smart card database\&. Match by ATR and ATR mask\&. "
.ti -1c
.RI "virtual void \fBSmartcards::WinSCard::IntroduceCardType\fP (const QString &cardName, const QByteArray &cardAtr, QUuid *pguidPrimaryProvider=nullptr)"
.br
.RI "Introduces a smart card to the smart card subsystem (for the active user) by adding it to the smart card database\&. Match by ATR\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void Smartcards::WinSCard::AddReaderToGroup (const QString & ReaderName, const QString & GroupName)\fC [virtual]\fP"

.PP
Adds a reader to group to 'GroupName'\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIReaderName\fP Name of the reader\&. 
.br
\fIGroupName\fP Name of the group\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::ForgetCardType (const QString & cardName)\fC [virtual]\fP"

.PP
Removes an introduced smart card from the smart card subsystem\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardName\fP Name of the card\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::ForgetReader (const QString & ReaderName)\fC [virtual]\fP"

.PP
removes a previously introduced reader from control by the smart card subsystem\&. It is removed from the smart card database, including from any reader group that it may have been added to\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIReaderName\fP Name of the reader\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::ForgetReaderGroup (const QString & GroupName)\fC [virtual]\fP"

.PP
Removes a previously introduced smart card reader group from the smart card subsystem\&. Although this function automatically clears all readers from the group, it does not affect the existence of the individual readers in the database\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIGroupName\fP Name of the group\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::IntroduceCardType (const QString & cardName, const QVector< QUuid > & guidInterfaces, const QByteArray & cardAtr, const QByteArray & cardAtrMask, QUuid * pguidPrimaryProvider = \fCnullptr\fP)\fC [virtual]\fP"

.PP
Introduces a smart card to the smart card subsystem (for the active user) by adding it to the smart card database\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardName\fP Name of the card\&. 
.br
\fIguidInterfaces\fP Array of identifiers (GUIDs) that identify the interfaces supported by the smart card\&. 
.br
\fIcardAtr\fP The card ATR\&. 
.br
\fIcardAtrMask\fP The card ATR mask\&. 
.br
\fIpguidPrimaryProvider\fP If non-null, the pointer to the identifier (GUID) for the smart card's primary service provider\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::IntroduceCardType (const QString & cardName, const QVector< QUuid > & guidInterfaces, const QByteArray & cardAtr, QUuid * pguidPrimaryProvider = \fCnullptr\fP)\fC [virtual]\fP"

.PP
Introduces a smart card to the smart card subsystem (for the active user) by adding it to the smart card database\&. Match by ATR and interfaces specified\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardName\fP Name of the card\&. 
.br
\fIguidInterfaces\fP Array of identifiers (GUIDs) that identify the interfaces supported by the smart card\&. 
.br
\fIcardAtr\fP The card ATR\&. 
.br
\fIpguidPrimaryProvider\fP If non-null, the pointer to the identifier (GUID) for the smart card's primary service provider\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::IntroduceCardType (const QString & cardName, const QByteArray & cardAtr, const QByteArray & cardAtrMask, QUuid * pguidPrimaryProvider = \fCnullptr\fP)\fC [virtual]\fP"

.PP
Introduces a smart card to the smart card subsystem (for the active user) by adding it to the smart card database\&. Match by ATR and ATR mask\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardName\fP Name of the card\&. 
.br
\fIcardAtr\fP The card ATR\&. 
.br
\fIcardAtrMask\fP The card ATR mask\&. 
.br
\fIpguidPrimaryProvider\fP If non-null, the pointer to the identifier (GUID) for the smart card's primary service provider\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::IntroduceCardType (const QString & cardName, const QByteArray & cardAtr, QUuid * pguidPrimaryProvider = \fCnullptr\fP)\fC [virtual]\fP"

.PP
Introduces a smart card to the smart card subsystem (for the active user) by adding it to the smart card database\&. Match by ATR\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardName\fP Name of the card\&. 
.br
\fIcardAtr\fP The card ATR\&. 
.br
\fIpguidPrimaryProvider\fP If non-null, the pointer to the identifier (GUID) for the smart card's primary service provider\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::IntroduceReader (const QString & ReaderName, const QString & DeviceName)\fC [virtual]\fP"

.PP
Introduces a new name for an existing smart card reader\&. 
.PP
\fBWarning:\fP
.RS 4
Smart card readers are automatically introduced to the system; a smart card reader vendor's setup program can also introduce a smart card reader to the system\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIReaderName\fP Name of the reader\&. 
.br
\fIDeviceName\fP Name of the device\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::IntroduceReaderGroup (const QString & GroupName)\fC [virtual]\fP"

.PP
Introduces a reader group to the smart card subsystem\&. However, the reader group is not created until the group is specified when adding a reader to the smart card database\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIGroupName\fP Name of the group\&. 
.RE
.PP

.SS "void Smartcards::WinSCard::RemoveReaderFromGroup (const QString & ReaderName, const QString & GroupName)\fC [virtual]\fP"

.PP
Removes a reader from an existing reader group\&. This function has no effect on the reader\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIReaderName\fP Name of the reader\&. 
.br
\fIGroupName\fP Name of the group\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
