.TH "scdb_funcs" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scdb_funcs \- Smart Card Database Query Functions
.SS "Functions"

.in +1c
.ti -1c
.RI "virtual QStringList \fBSmartcards::WinSCard::ListReaders\fP (void)"
.br
.RI "Get list readers\&. "
.ti -1c
.RI "virtual QStringList \fBSmartcards::WinSCard::ListReaderGroups\fP (void)"
.br
.RI "Get list reader groups\&. "
.ti -1c
.RI "virtual QUuid \fBSmartcards::WinSCard::GetProviderId\fP (const QString &cardName)"
.br
.RI "Gets provider GUID\&. "
.ti -1c
.RI "virtual QStringList \fBSmartcards::WinSCard::ListCards\fP (const QByteArray &cardAtr, const QVector< QUuid > &guidInterfaces)"
.br
.RI "Searches the smart card database and provides a list of named cards previously introduced to the system by the user\&. Match ATR an support the interfaces specified\&. "
.ti -1c
.RI "virtual QStringList \fBSmartcards::WinSCard::ListCards\fP (const QVector< QUuid > &guidInterfaces)"
.br
.RI "Searches the smart card database and provides a list of named cards previously introduced to the system by the user\&. Search for interfaces specified\&. "
.ti -1c
.RI "virtual QStringList \fBSmartcards::WinSCard::ListCards\fP (const QByteArray &cardAtr)"
.br
.RI "Searches the smart card database and provides a list of named cards previously introduced to the system by the user\&. Match for ATR\&. "
.ti -1c
.RI "virtual QStringList \fBSmartcards::WinSCard::ListCards\fP (void)"
.br
.RI "Searches the smart card database and provides a list of named cards previously introduced to the system by the user\&. "
.ti -1c
.RI "virtual QVector< QUuid > \fBSmartcards::WinSCard::ListInterfaces\fP (const QString &cardName)"
.br
.RI "Provides a list of interfaces supplied by a given card\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "QUuid Smartcards::WinSCard::GetProviderId (const QString & cardName)\fC [virtual]\fP"

.PP
Gets provider GUID\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardName\fP Name of the card\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The provider GUID\&. 
.RE
.PP

.SS "QStringList Smartcards::WinSCard::ListCards (const QByteArray & cardAtr, const QVector< QUuid > & guidInterfaces)\fC [virtual]\fP"

.PP
Searches the smart card database and provides a list of named cards previously introduced to the system by the user\&. Match ATR an support the interfaces specified\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardAtr\fP The card ATR\&. 
.br
\fIguidInterfaces\fP The unique identifier interfaces\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A list of cards names\&. 
.RE
.PP

.SS "QStringList Smartcards::WinSCard::ListCards (const QVector< QUuid > & guidInterfaces)\fC [virtual]\fP"

.PP
Searches the smart card database and provides a list of named cards previously introduced to the system by the user\&. Search for interfaces specified\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIguidInterfaces\fP The unique identifier interfaces\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A list of cards names 
.RE
.PP

.SS "QStringList Smartcards::WinSCard::ListCards (const QByteArray & cardAtr)\fC [virtual]\fP"

.PP
Searches the smart card database and provides a list of named cards previously introduced to the system by the user\&. Match for ATR\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardAtr\fP The card atr\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A list of cards names 
.RE
.PP

.SS "QStringList Smartcards::WinSCard::ListCards (void)\fC [virtual]\fP"

.PP
Searches the smart card database and provides a list of named cards previously introduced to the system by the user\&. 
.PP
\fBReturns:\fP
.RS 4
A list of cards names 
.RE
.PP

.SS "QVector< QUuid > Smartcards::WinSCard::ListInterfaces (const QString & cardName)\fC [virtual]\fP"

.PP
Provides a list of interfaces supplied by a given card\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcardName\fP Name of the card\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Vector of interfaces supported by the card 
.RE
.PP

.SS "QStringList Smartcards::WinSCard::ListReaderGroups (void)\fC [virtual]\fP"

.PP
Get list reader groups\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A list of reader groups\&. 
.RE
.PP

.SS "QStringList Smartcards::WinSCard::ListReaders (void)\fC [virtual]\fP"

.PP
Get list readers\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSCardException\fP\fP Thrown when a Card error condition occurs and throwErrors is set true\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A list of readers names\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
