.TH "Smartcards::APDUCommand" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Smartcards::APDUCommand \- This class represents the APDU command\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <APDUCommand\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAPDUCommand\fP (BYTE bCla, BYTE bIns, BYTE bP1=0, BYTE bP2=0, const QByteArray &vData=QByteArray(), BYTE nLe=0)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBAPDUCommand\fP (BYTE bCla, BYTE bIns, BYTE bP1, BYTE bP2, std::initializer_list< char > ilist, BYTE nLe=0)"
.br
.RI "Constructor with initilizer list\&. "
.ti -1c
.RI "virtual \fB~APDUCommand\fP (void)"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBsetCommand\fP (BYTE bCla, BYTE bIns, BYTE bP1=0, BYTE bP2=0, const QByteArray &vData=QByteArray(), BYTE nLe=0)"
.br
.RI "Set a APDU command\&. "
.ti -1c
.RI "QString \fBtoString\fP (void) const"
.br
.RI "Convert this object into a string representation\&. "
.ti -1c
.RI "void \fBsetClass\fP (BYTE cls)"
.br
.RI "Class(CLA) byte set property\&. "
.ti -1c
.RI "void \fBsetIns\fP (BYTE ins)"
.br
.RI "Instruction(INS) byte set property\&. "
.ti -1c
.RI "void \fBsetP1\fP (BYTE p1)"
.br
.RI "First param(P1) byte set property\&. "
.ti -1c
.RI "void \fBsetP2\fP (BYTE p2)"
.br
.RI "Second param(P2) byte set property\&. "
.ti -1c
.RI "void \fBsetLe\fP (BYTE le)"
.br
.RI "Number of data set property\&. "
.ti -1c
.RI "void \fBsetData\fP (const QByteArray &data)"
.br
.RI "Data to send to the card set property\&. "
.ti -1c
.RI "BYTE \fBgetClass\fP (void) const"
.br
.RI "Class(CLA) byte get property\&. "
.ti -1c
.RI "BYTE \fBgetIns\fP (void) const"
.br
.RI "Instruction(INS) byte get property\&. "
.ti -1c
.RI "BYTE \fBgetP1\fP (void) const"
.br
.RI "First param(P1) byte get property\&. "
.ti -1c
.RI "BYTE \fBgetP2\fP (void) const"
.br
.RI "Second param(P2) byte get property\&. "
.ti -1c
.RI "BYTE \fBgetLe\fP (void) const"
.br
.RI "Number of data byte get property\&. "
.ti -1c
.RI "QByteArray \fBgetData\fP (void) const"
.br
.RI "Data to send to the card get property\&. "
.ti -1c
.RI "size_t \fBgetDataSize\fP (void) const"
.br
.RI "Get size of data in the byte array\&. "
.ti -1c
.RI "bool \fBemptyData\fP (void) const"
.br
.RI "Check empty data\&. "
.ti -1c
.RI "QByteArray \fBcreateCommandVector\fP (void) const"
.br
.RI "Create byte array contains the APDU command for transmit to the card\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBAPDU_MIN_LENGTH\fP = 4"
.br
.RI "Minimum size in bytes of an APDU command\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class represents the APDU command\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "APDUCommand::APDUCommand (BYTE bCla, BYTE bIns, BYTE bP1 = \fC0\fP, BYTE bP2 = \fC0\fP, const QByteArray & vData = \fCQByteArray()\fP, BYTE nLe = \fC0\fP)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbCla\fP Class(CLA) byte of APDU command 
.br
\fIbIns\fP Instruction(INS) byte of APDU command 
.br
\fIbP1\fP First param(P1) byte of APDU command\&. Default value is 0\&. 
.br
\fIbP2\fP Second param(P2) byte of APDU command\&. Default value is 0\&. 
.br
\fIvData\fP Data to send to the card if any, empty if no data to send\&. Default is empty\&. 
.br
\fInLe\fP Number of data expected, 0 if none\&. Default value is 0\&. 
.RE
.PP

.SS "APDUCommand::APDUCommand (BYTE bCla, BYTE bIns, BYTE bP1, BYTE bP2, std::initializer_list< char > ilist, BYTE nLe = \fC0\fP)"

.PP
Constructor with initilizer list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbCla\fP Class(CLA) byte of APDU command 
.br
\fIbIns\fP Instruction(INS) byte of APDU command 
.br
\fIbP1\fP First param(P1) byte of APDU command 
.br
\fIbP2\fP Second param(P2) byte of APDU command 
.br
\fIilist\fP Initializer list of bytes contains data to send to the card\&. 
.br
\fInLe\fP Number of data expected, 0 if none\&. Default value is 0\&. 
.RE
.PP

.SS "APDUCommand::~APDUCommand (void)\fC [virtual]\fP"

.PP
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "QByteArray APDUCommand::createCommandVector (void) const"

.PP
Create byte array contains the APDU command for transmit to the card\&. 
.PP
\fBReturns:\fP
.RS 4
Byte array contains the APDU command 
.RE
.PP

.SS "bool Smartcards::APDUCommand::emptyData (void) const\fC [inline]\fP"

.PP
Check empty data\&. 
.PP
\fBReturns:\fP
.RS 4
true if data empty, otherwise false 
.RE
.PP

.SS "BYTE Smartcards::APDUCommand::getClass (void) const\fC [inline]\fP"

.PP
Class(CLA) byte get property\&. 
.PP
\fBReturns:\fP
.RS 4
Class(CLA) byte 
.RE
.PP

.SS "QByteArray Smartcards::APDUCommand::getData (void) const\fC [inline]\fP"

.PP
Data to send to the card get property\&. 
.PP
\fBReturns:\fP
.RS 4
Data to send to the card 
.RE
.PP

.SS "size_t Smartcards::APDUCommand::getDataSize (void) const\fC [inline]\fP"

.PP
Get size of data in the byte array\&. 
.PP
\fBReturns:\fP
.RS 4
Class(CLA) byte 
.RE
.PP

.SS "BYTE Smartcards::APDUCommand::getIns (void) const\fC [inline]\fP"

.PP
Instruction(INS) byte get property\&. 
.PP
\fBReturns:\fP
.RS 4
Instruction(INS) byte 
.RE
.PP

.SS "BYTE Smartcards::APDUCommand::getLe (void) const\fC [inline]\fP"

.PP
Number of data byte get property\&. 
.PP
\fBReturns:\fP
.RS 4
Number of data byte 
.RE
.PP

.SS "BYTE Smartcards::APDUCommand::getP1 (void) const\fC [inline]\fP"

.PP
First param(P1) byte get property\&. 
.PP
\fBReturns:\fP
.RS 4
First param(P1) byte 
.RE
.PP

.SS "BYTE Smartcards::APDUCommand::getP2 (void) const\fC [inline]\fP"

.PP
Second param(P2) byte get property\&. 
.PP
\fBReturns:\fP
.RS 4
Second param(P2) byte 
.RE
.PP

.SS "void Smartcards::APDUCommand::setClass (BYTE cls)\fC [inline]\fP"

.PP
Class(CLA) byte set property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcls\fP Class(CLA) byte 
.RE
.PP

.SS "void APDUCommand::setCommand (BYTE bCla, BYTE bIns, BYTE bP1 = \fC0\fP, BYTE bP2 = \fC0\fP, const QByteArray & vData = \fCQByteArray()\fP, BYTE nLe = \fC0\fP)"

.PP
Set a APDU command\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbCla\fP Class(CLA) byte of APDU command 
.br
\fIbIns\fP Instruction(INS) byte of APDU command 
.br
\fIbP1\fP First param(P1) byte of APDU command\&. Default value is 0\&. 
.br
\fIbP2\fP Second param(P2) byte of APDU command\&. Default value is 0\&. 
.br
\fIvData\fP Data to send to the card if any, empty if no data to send\&. Default is empty\&. 
.br
\fInLe\fP Number of data expected, 0 if none\&. Default value is 0\&. 
.RE
.PP

.SS "void Smartcards::APDUCommand::setData (const QByteArray & data)\fC [inline]\fP"

.PP
Data to send to the card set property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data to send to the card 
.RE
.PP

.SS "void Smartcards::APDUCommand::setIns (BYTE ins)\fC [inline]\fP"

.PP
Instruction(INS) byte set property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIins\fP Instruction(INS) byte 
.RE
.PP

.SS "void Smartcards::APDUCommand::setLe (BYTE le)\fC [inline]\fP"

.PP
Number of data set property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIle\fP Number of data 
.RE
.PP

.SS "void Smartcards::APDUCommand::setP1 (BYTE p1)\fC [inline]\fP"

.PP
First param(P1) byte set property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp1\fP First param(P1) byte 
.RE
.PP

.SS "void Smartcards::APDUCommand::setP2 (BYTE p2)\fC [inline]\fP"

.PP
Second param(P2) byte set property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp2\fP Second param(P2) byte 
.RE
.PP

.SS "QString APDUCommand::toString (void) const"

.PP
Convert this object into a string representation\&. 
.PP
\fBReturns:\fP
.RS 4
Formatted string with APDU command in hex 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "const int Smartcards::APDUCommand::APDU_MIN_LENGTH = 4\fC [static]\fP"

.PP
Minimum size in bytes of an APDU command\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
