.TH "Smartcards::APDUResponse" 3 "Tue Nov 22 2016" "QWinSCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Smartcards::APDUResponse \- This class represents the APDU response sent by the card\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <APDUResponse\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAPDUResponse\fP (const QByteArray &vData=QByteArray())"
.br
.RI "Constructor from the byte data sent back by the card\&. "
.ti -1c
.RI "\fBAPDUResponse\fP (const \fBAPDUResponse\fP &response)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBAPDUResponse\fP (BYTE sw1, BYTE sw2)"
.br
.RI "Constructor from the two status bytes\&. "
.ti -1c
.RI "\fBAPDUResponse\fP & \fBoperator=\fP (const \fBAPDUResponse\fP &other)"
.br
.RI "Assignment operator\&. "
.ti -1c
.RI "\fB~APDUResponse\fP (void)"
.br
.RI "Destructor\&. "
.ti -1c
.RI "QByteArray \fBgetData\fP (void) const"
.br
.RI "Response data get property\&. "
.ti -1c
.RI "void \fBsetData\fP (const QByteArray &vData)"
.br
.RI "Response data set property\&. "
.ti -1c
.RI "BYTE \fBgetSW1\fP (void) const"
.br
.RI "SW1 byte get property\&. "
.ti -1c
.RI "BYTE \fBgetSW2\fP (void) const"
.br
.RI "SW2 byte get property\&. "
.ti -1c
.RI "WORD \fBgetStatus\fP (void) const"
.br
.ti -1c
.RI "QString \fBtoString\fP (void) const"
.br
.RI "Convert this object into a string representation\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSW_LENGTH\fP = 2"
.br
.RI "Status bytes length\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class represents the APDU response sent by the card\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "APDUResponse::APDUResponse (const QByteArray & vData = \fCQByteArray()\fP)"

.PP
Constructor from the byte data sent back by the card\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvData\fP Byte array of data from the card 
.RE
.PP

.SS "Smartcards::APDUResponse::APDUResponse (const \fBAPDUResponse\fP & response)"

.PP
Copy constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIresponse\fP The response\&. 
.RE
.PP

.SS "Smartcards::APDUResponse::APDUResponse (BYTE sw1, BYTE sw2)"

.PP
Constructor from the two status bytes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsw1\fP First status byte 
.br
\fIsw2\fP Second status byte 
.RE
.PP

.SS "Smartcards::APDUResponse::~APDUResponse (void)"

.PP
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "QByteArray Smartcards::APDUResponse::getData (void) const\fC [inline]\fP"

.PP
Response data get property\&. 
.PP
\fBReturns:\fP
.RS 4
byte array of data sent by the card minus the 2 status bytes (SW1, SW2)\&. Is empty if no data were sent by the card\&. 
.RE
.PP

.SS "WORD Smartcards::APDUResponse::getStatus (void) const\fC [inline]\fP"

.SS "BYTE Smartcards::APDUResponse::getSW1 (void) const\fC [inline]\fP"

.PP
SW1 byte get property\&. 
.PP
\fBReturns:\fP
.RS 4
first status byte 
.RE
.PP

.SS "BYTE Smartcards::APDUResponse::getSW2 (void) const\fC [inline]\fP"

.PP
SW2 byte get property\&. Status get property\&.
.PP
\fBReturns:\fP
.RS 4
second status byte
.PP
status word 
.RE
.PP

.SS "\fBAPDUResponse\fP & Smartcards::APDUResponse::operator= (const \fBAPDUResponse\fP & other)"

.PP
Assignment operator\&. 
.PP
\fBParameters:\fP
.RS 4
\fIother\fP The other response object\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A shallow copy of this object\&. 
.RE
.PP

.SS "void Smartcards::APDUResponse::setData (const QByteArray & vData)"

.PP
Response data set property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvData\fP Byte array of data from the card 
.RE
.PP

.SS "QString Smartcards::APDUResponse::toString (void) const"

.PP
Convert this object into a string representation\&. 
.PP
\fBReturns:\fP
.RS 4
A QString that represents this object\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "const int Smartcards::APDUResponse::SW_LENGTH = 2\fC [static]\fP"

.PP
Status bytes length\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for QWinSCard from the source code\&.
